In [ ]:
# Step 1 — Install libraries
!pip install transformers
!pip install datasets
!pip install sentencepiece
!pip install jiwer
!pip install ctranslate2
!pip install gradio
!pip install accelerate
!pip install huggingface_hub

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (0.1.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 49.8 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, jiwer
Successfully installed jiwer-4.0.0 rapidfuzz-3.14.3
Collecting ctranslate2
  Downloading ctranslate2-4.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from ctranslate2) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from ctranslate2) (2.0.2)
Requirement already satisfied: pyyaml<7,>=5.3 in /usr/local/lib/python3.12/dist-packages (from ctranslate2) (6.0.3)
Downloading ctranslate2-4.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (39.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.0/39.0 MB 21.0 MB/s eta 0:00:00
Installing collected packages: ctranslate2
Successfully installed ctranslate2-4.7.1
Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.12.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.135.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.5.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.0)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.5)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.41.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.3.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.5.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)

In [ ]:
# dowload dataset
!git clone https://huggingface.co/datasets/ai4bharat/Aksharantar

Cloning into 'Aksharantar'...
remote: Enumerating objects: 156, done.
remote: Total 156 (delta 0), reused 0 (delta 0), pack-reused 156 (from 1)
Receiving objects: 100% (156/156), 21.27 KiB | 10.63 MiB/s, done.
Resolving deltas: 100% (56/56), done.
Filtering content: 100% (21/21), 695.41 MiB | 61.21 MiB/s, done.

In [ ]:
import os
os.listdir("Aksharantar")

['README.md',
 '.git',
 'mni.zip',
 'kas.zip',
 'kan.zip',
 'hin.zip',
 'ori.zip',
 'tam.zip',
 'pan.zip',
 'mai.zip',
 'ben.zip',
 'brx.zip',
 'san.zip',
 'nep.zip',
 'urd.zip',
 'tel.zip',
 'guj.zip',
 'mar.zip',
 'sid.zip',
 'asm.zip',
 'mal.zip',
 '.gitattributes',
 'kok.zip',
 'doi.zip']

In [ ]:
!unzip Aksharantar/hin.zip
!unzip Aksharantar/ben.zip
!unzip Aksharantar/tam.zip

Archive:  Aksharantar/hin.zip
  inflating: hin_test.json
  inflating: hin_train.json
  inflating: hin_valid.json
Archive:  Aksharantar/ben.zip
  inflating: ben_test.json
  inflating: ben_train.json
  inflating: ben_valid.json
Archive:  Aksharantar/tam.zip
  inflating: tam_test.json
  inflating: tam_train.json
  inflating: tam_valid.json

In [ ]:
import pandas as pd

hi = pd.read_json("/content/hin_train.json", lines=True)
bn = pd.read_json("/content/ben_train.json", lines=True)
ta = pd.read_json("/content/tam_train.json", lines=True)

In [ ]:
hi.head()

  unique_identifier native word english word    source  score
0              hin1    जन्मदिवस   janamdivas  Dakshina    NaN
1              hin2       रक्खा        rakha  Dakshina    NaN
2              hin3    मिलीजुली     milijuli  Dakshina    NaN
3              hin4      जांचों     jaanchon  Dakshina    NaN
4              hin5       चमकता     chamkata  Dakshina    NaN

In [ ]:
hi = hi[["english word", "native word"]].head(10000).copy()
bn = bn[["english word", "native word"]].head(10000).copy()
ta = ta[["english word", "native word"]].head(10000).copy()

In [ ]:
hi.head()

  english word native word
0   janamdivas    जन्मदिवस
1        rakha       रक्खा
2     milijuli    मिलीजुली
3     jaanchon      जांचों
4     chamkata       चमकता

In [ ]:
def prepare(df, lang):
    return pd.DataFrame({
        "input": [f"transliterate to {lang}: {x}" for x in df["english word"].astype(str)],
        "target": [str(x) for x in df["native word"]]
    })

df_hi = prepare(hi, "hindi")
df_bn = prepare(bn, "bengali")
df_ta = prepare(ta, "tamil")

df = pd.concat([df_hi, df_bn, df_ta], ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
print(df.head())
print(df.shape)

                                   input         target
0        transliterate to hindi: evready         एवरेडी
1       transliterate to tamil: selgirar     செல்கிறார்
2  transliterate to tamil: tholkaappiyam  தொல்காப்பியம்
3      transliterate to tamil: pesiyavar       பேசியவர்
4          transliterate to hindi: paaun           पाऊं
(30000, 2)

In [ ]:
df_hi = prepare(hi,"hindi")
df_bn = prepare(bn,"bengali")
df_ta = prepare(ta,"tamil")

In [ ]:
from datasets import Dataset

dataset = Dataset.from_pandas(df, preserve_index=False)

In [ ]:
dataset

Dataset({
    features: ['input', 'target'],
    num_rows: 30000
})

In [ ]:
dataset = dataset.train_test_split(test_size=0.1, seed=42)

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['input', 'target'],
        num_rows: 27000
    })
    test: Dataset({
        features: ['input', 'target'],
        num_rows: 3000
    })
})

In [ ]:
print(dataset["train"][0])

{'input': 'transliterate to tamil: aatchiyaalargalin', 'target': 'ஆட்சியாளர்களின்'}

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
model.config.use_cache = False

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/172 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
def tokenize(batch):
    model_inputs = tokenizer(
        batch["input"],
        truncation=True,
        max_length=32
    )

    labels = tokenizer(
        text_target=batch["target"],
        truncation=True,
        max_length=32
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
tokenized_dataset = dataset.map(
    tokenize,
    batched=True,
    remove_columns=["input", "target"]
)

print(tokenized_dataset)
print(tokenized_dataset["train"][0])

Map:   0%|          | 0/27000 [00:00<?, ? examples/s]

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 27000
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 3000
    })
})
{'input_ids': [119, 117, 100, 113, 118, 111, 108, 119, 104, 117, 100, 119, 104, 35, 119, 114, 35, 119, 100, 112, 108, 111, 61, 35, 100, 100, 119, 102, 107, 108, 124, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [227, 177, 137, 227, 177, 162, 227, 178, 144, 227, 177, 157, 227, 177, 194, 227, 177, 178, 227, 177, 193, 227, 177, 182, 227, 177, 179, 227, 178, 144, 227, 1]}

In [ ]:
sample = tokenized_dataset["train"][0]
print("input_ids:", sample["input_ids"][:10])
print("labels:", sample["labels"][:10])
print("decoded input:", tokenizer.decode(sample["input_ids"], skip_special_tokens=True))
print("decoded label:", tokenizer.decode([x for x in sample["labels"] if x != -100], skip_special_tokens=True))

input_ids: [119, 117, 100, 113, 118, 111, 108, 119, 104, 117]
labels: [227, 177, 137, 227, 177, 162, 227, 178, 144, 227]
decoded input: transliterate to tamil: aatchiy
decoded label: ஆட்சியாளர்

In [ ]:
tokenized_dataset.save_to_disk("tokenized_dataset")

Saving the dataset (0/1 shards):   0%|          | 0/27000 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/3000 [00:00<?, ? examples/s]

In [ ]:
from datasets import load_from_disk
tokenized_dataset = load_from_disk("tokenized_dataset")

In [ ]:
sample = tokenized_dataset["train"][0]

print("INPUT IDS:", sample["input_ids"][:15])
print("LABEL IDS:", sample["labels"][:15])

print("DECODED INPUT:")
print(tokenizer.decode(sample["input_ids"], skip_special_tokens=True))

print("DECODED LABEL:")
print(tokenizer.decode(sample["labels"], skip_special_tokens=True))

INPUT IDS: [119, 117, 100, 113, 118, 111, 108, 119, 104, 117, 100, 119, 104, 35, 119]
LABEL IDS: [227, 177, 137, 227, 177, 162, 227, 178, 144, 227, 177, 157, 227, 177, 194]
DECODED INPUT:
transliterate to tamil: aatchiy
DECODED LABEL:
ஆட்சியாளர்

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

In [ ]:
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments
import torch

training_args = Seq2SeqTrainingArguments(
    output_dir="./results_byt5",
    learning_rate=1e-4,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100,
    predict_with_generate=True,
    fp16=False,
    report_to="none"
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    data_collator=data_collator
)

In [ ]:
print(df.head(5))
print(df.isna().sum())
print(df["target"].head(10).tolist())
print(df["target"].str.len().describe())

                                   input         target
0        transliterate to hindi: evready         एवरेडी
1       transliterate to tamil: selgirar     செல்கிறார்
2  transliterate to tamil: tholkaappiyam  தொல்காப்பியம்
3      transliterate to tamil: pesiyavar       பேசியவர்
4          transliterate to hindi: paaun           पाऊं
input     0
target    0
dtype: int64
['एवरेडी', 'செல்கிறார்', 'தொல்காப்பியம்', 'பேசியவர்', 'पाऊं', 'कत्याल', 'अग्रसेन', 'क्रियाएं', 'সূর্যাস্তের', 'ঘটক']
count    30000.000000
mean         7.887500
std          2.896686
min          1.000000
25%          6.000000
50%          7.000000
75%         10.000000
max         25.000000
Name: target, dtype: float64

In [ ]:
print(dataset["train"][0])
print(dataset["train"][1])

{'input': 'transliterate to tamil: aatchiyaalargalin', 'target': 'ஆட்சியாளர்களின்'}
{'input': 'transliterate to bengali: seeksan', 'target': 'সেকশন'}

In [ ]:
print(tokenized_dataset["train"][0])

{'input_ids': [119, 117, 100, 113, 118, 111, 108, 119, 104, 117, 100, 119, 104, 35, 119, 114, 35, 119, 100, 112, 108, 111, 61, 35, 100, 100, 119, 102, 107, 108, 124, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [227, 177, 137, 227, 177, 162, 227, 178, 144, 227, 177, 157, 227, 177, 194, 227, 177, 178, 227, 177, 193, 227, 177, 182, 227, 177, 179, 227, 178, 144, 227, 1]}

In [ ]:
sample = tokenized_dataset["train"][0]

print("decoded input:")
print(tokenizer.decode(sample["input_ids"], skip_special_tokens=True))

print("raw labels:")
print(sample["labels"])

valid_labels = [x for x in sample["labels"] if x != -100]
print("valid label ids:")
print(valid_labels)

print("decoded label:")
print(tokenizer.decode(valid_labels, skip_special_tokens=True))

decoded input:
transliterate to tamil: aatchiy
raw labels:
[227, 177, 137, 227, 177, 162, 227, 178, 144, 227, 177, 157, 227, 177, 194, 227, 177, 178, 227, 177, 193, 227, 177, 182, 227, 177, 179, 227, 178, 144, 227, 1]
valid label ids:
[227, 177, 137, 227, 177, 162, 227, 178, 144, 227, 177, 157, 227, 177, 194, 227, 177, 178, 227, 177, 193, 227, 177, 182, 227, 177, 179, 227, 178, 144, 227, 1]
decoded label:
ஆட்சியாளர்

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=5064, training_loss=0.7485408022128763, metrics={'train_runtime': 2201.2207, 'train_samples_per_second': 36.798, 'train_steps_per_second': 2.301, 'total_flos': 4651169734656000.0, 'train_loss': 0.7485408022128763, 'epoch': 3.0})

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

def transliterate(text, lang):
    prompt = f"transliterate to {lang}: {text}"
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=32)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=20,
            num_beams=4
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [ ]:
print(transliterate("ram", "hindi"))
print(transliterate("ram", "bengali"))
print(transliterate("ram", "tamil"))
print(transliterate("namaste", "hindi"))
print(transliterate("krishna", "hindi"))

राम
রাম
ரம்
नमस्ते
क्रिश्

In [ ]:
from jiwer import cer,wer

refs=["राम","रम"]
preds=["राम","राम"]

print("CER:",cer(refs,preds))
print("WER:",wer(refs,preds))

CER: 0.2
WER: 0.5

In [ ]:
save_dir = "final_model"

trainer.save_model(save_dir)
tokenizer.save_pretrained(save_dir)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('final_model/tokenizer_config.json', 'final_model/added_tokens.json')

In [ ]:
!ct2-transformers-converter \
  --model final_model \
  --output_dir ct2_model \
  --quantization int8

Loading weights: 100% 172/172 [00:00<00:00, 355.42it/s, Materializing param=shared.weight]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [ ]:
import os
print(os.listdir(save_dir))

['generation_config.json', 'tokenizer_config.json', 'model.safetensors', 'config.json', 'training_args.bin', 'added_tokens.json']

In [ ]:
import os

def get_folder_size_mb(folder):
    total = 0
    for root, dirs, files in os.walk(folder):
        for file in files:
            path = os.path.join(root, file)
            total += os.path.getsize(path)
    return total / (1024 * 1024)

orig_size = get_folder_size_mb("final_model")
ct2_size = get_folder_size_mb("ct2_model")

print(f"Original model size: {orig_size:.2f} MB")
print(f"CTranslate2 model size: {ct2_size:.2f} MB")
print(f"Reduction: {((orig_size - ct2_size) / orig_size) * 100:.2f}%")

Original model size: 1147.40 MB
CTranslate2 model size: 287.21 MB
Reduction: 74.97%

In [ ]:
import time
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

hf_tokenizer = AutoTokenizer.from_pretrained("final_model")
hf_model = AutoModelForSeq2SeqLM.from_pretrained("final_model").to(device)
hf_model.eval()

def hf_transliterate(text, lang):
    prompt = f"transliterate to {lang}: {text}"
    inputs = hf_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=64)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = hf_model.generate(**inputs, max_new_tokens=20, num_beams=4)
    return hf_tokenizer.decode(outputs[0], skip_special_tokens=True)

samples = [
    ("ram", "hindi"),
    ("namaste", "hindi"),
    ("krishna", "hindi"),
    ("bharat", "bengali"),
    ("aatchiyaalargalin", "tamil"),
] * 10

start = time.time()
for text, lang in samples:
    _ = hf_transliterate(text, lang)
hf_time = time.time() - start

print("HF total time:", hf_time)
print("HF avg latency per request:", hf_time / len(samples))

Loading weights:   0%|          | 0/172 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

HF total time: 21.007375717163086
HF avg latency per request: 0.4201475143432617

In [ ]:
import time
import ctranslate2
from transformers import AutoTokenizer

ct2_tokenizer = AutoTokenizer.from_pretrained("final_model")
translator = ctranslate2.Translator("ct2_model", device="cpu")

def ct2_transliterate(text, lang):
    prompt = f"transliterate to {lang}: {text}"
    input_ids = ct2_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=64)["input_ids"][0]
    tokens = ct2_tokenizer.convert_ids_to_tokens(input_ids)
    results = translator.translate_batch([tokens], max_decoding_length=20, beam_size=4)
    output_tokens = results[0].hypotheses[0]
    return ct2_tokenizer.decode(ct2_tokenizer.convert_tokens_to_ids(output_tokens), skip_special_tokens=True)

samples = [
    ("ram", "hindi"),
    ("namaste", "hindi"),
    ("krishna", "hindi"),
    ("bharat", "bengali"),
    ("aatchiyaalargalin", "tamil"),
] * 10

start = time.time()
for text, lang in samples:
    _ = ct2_transliterate(text, lang)
ct2_time = time.time() - start

print("CT2 total time:", ct2_time)
print("CT2 avg latency per request:", ct2_time / len(samples))

CT2 total time: 46.610137701034546
CT2 avg latency per request: 0.932202754020691

In [ ]:
speed_gain = ((hf_time - ct2_time) / hf_time) * 100
print(f"Speed gain: {speed_gain:.2f}%")

Speed gain: -121.88%

In [ ]:
from jiwer import cer, wer

test_rows = df.sample(200, random_state=42)

preds = []
refs = []

for _, row in test_rows.iterrows():
    full_input = row["input"]
    target = row["target"]

    prefix = "transliterate to "
    rest = full_input[len(prefix):]
    lang, text = rest.split(": ", 1)

    pred = hf_transliterate(text, lang)

    preds.append(pred)
    refs.append(target)

exact_matches = sum(p == r for p, r in zip(preds, refs))
accuracy = exact_matches / len(refs)

print("Accuracy:", accuracy)
print("CER:", cer(refs, preds))
print("WER:", wer(refs, preds))

Accuracy: 0.09
CER: 0.40998104864181933
WER: 0.91

In [ ]:
ct2_preds = []

for _, row in test_rows.iterrows():
    full_input = row["input"]
    target = row["target"]

    prefix = "transliterate to "
    rest = full_input[len(prefix):]
    lang, text = rest.split(": ", 1)

    pred = ct2_transliterate(text, lang)
    ct2_preds.append(pred)

ct2_accuracy = sum(p == r for p, r in zip(ct2_preds, refs)) / len(refs)

print("CT2 Accuracy:", ct2_accuracy)
print("CT2 CER:", cer(refs, ct2_preds))
print("CT2 WER:", wer(refs, ct2_preds))

CT2 Accuracy: 0.075
CT2 CER: 0.4131396083385976
CT2 WER: 0.925

In [ ]:
# from huggingface_hub import notebook_login

# notebook_login()

In [ ]:
# model.push_to_hub("multilingual-transliteration")
# tokenizer.push_to_hub("multilingual-transliteration")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ypwt_lx/model.safetensors:   3%|3         | 39.9MB / 1.20GB

README.md: 0.00B [00:00, ?B/s]

CommitInfo(commit_url='https://huggingface.co/kunalkurve219/multilingual-transliteration/commit/a7353afdb34d8e5ea00751afd25818c1dead122f', commit_message='Upload tokenizer', commit_description='', oid='a7353afdb34d8e5ea00751afd25818c1dead122f', pr_url=None, repo_url=RepoUrl('https://huggingface.co/kunalkurve219/multilingual-transliteration', endpoint='https://huggingface.co', repo_type='model', repo_id='kunalkurve219/multilingual-transliteration'), pr_revision=None, pr_num=None)

In [ ]:
# !zip -r final_model.zip final_model

  adding: final_model/ (stored 0%)
  adding: final_model/generation_config.json (deflated 29%)
  adding: final_model/tokenizer_config.json (deflated 95%)
  adding: final_model/model.safetensors (deflated 8%)
  adding: final_model/config.json (deflated 49%)
  adding: final_model/training_args.bin (deflated 53%)
  adding: final_model/added_tokens.json (deflated 82%)

In [ ]:
# from google.colab import files
# files.download("final_model.zip")

In [ ]:
# !zip -r ct2_model.zip ct2_model

  adding: ct2_model/ (stored 0%)
  adding: ct2_model/shared_vocabulary.json (deflated 82%)
  adding: ct2_model/model.bin (deflated 10%)
  adding: ct2_model/config.json (deflated 44%)

In [ ]:
# from google.colab import files
# files.download("ct2_model.zip")

In [ ]:
# tokenizer.save_pretrained("tokenizer_only")

('tokenizer_only/tokenizer_config.json', 'tokenizer_only/added_tokens.json')

In [ ]:
# !zip -r tokenizer_only.zip tokenizer_only

  adding: tokenizer_only/ (stored 0%)
  adding: tokenizer_only/tokenizer_config.json (deflated 95%)
  adding: tokenizer_only/added_tokens.json (deflated 82%)